question_data = [
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "The Khajiit are a race of cat-like creatures from which epic series of role-playing games, set across the land of Tamriel?",
        "correct_answer": "The Elder Scrolls",
        "incorrect_answers": [
            "Lord of the Rings",
            "The Witcher",
            "Neverwinter Nights",
        ],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Vehicles",
        "question": "The full English name of the car manufacturer BMW is Bavarian Motor Works",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Animals",
        "question": "What is Grumpy Cat&#039;s real name?",
        "correct_answer": "Tardar Sauce",
        "incorrect_answers": ["Sauce", "Minnie", "Broccoli"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "Which game did NOT get financed via Crowdfunding?",
        "correct_answer": "Enter the Gungeon",
        "incorrect_answers": ["Town of Salem", "Undertale", "Tower Unite"],
    },
    {
        "type": "multiple",
        "difficulty": "medium",
        "category": "Entertainment: Video Games",
        "question": "How many permanent companions are there in the base game version of Fallout: New Vegas?",
        "correct_answer": "8",
        "incorrect_answers": ["7", "9", "6"],
    },
    {
        "type": "multiple",
        "difficulty": "medium",
        "category": "Entertainment: Video Games",
        "question": "In Portal, what color is the Morality Core?",
        "correct_answer": "Purple",
        "incorrect_answers": ["Red", "Yellow", "Blue"],
    },
    {
        "type": "multiple",
        "difficulty": "medium",
        "category": "History",
        "question": "Which Nazi General was known as the &quot;Desert Fox&quot;?",
        "correct_answer": "Erwin Rommel",
        "incorrect_answers": [
            "Gerd von Rundstadt",
            "Wilhelm Keitel",
            "Heinz Guderian ",
        ],
    },
    {
        "type": "multiple",
        "difficulty": "medium",
        "category": "General Knowledge",
        "question": "When was the Declaration of Independence approved by the Second Continental Congress?",
        "correct_answer": "July 4, 1776",
        "incorrect_answers": ["May 4, 1776", "June 4, 1776", "July 2, 1776"],
    },
    {
        "type": "multiple",
        "difficulty": "medium",
        "category": "History",
        "question": "Which country gifted the Statue of Liberty to the United States of America?",
        "correct_answer": "France",
        "incorrect_answers": ["Spain", "England", "Germany"],
    },
    {
        "type": "multiple",
        "difficulty": "medium",
        "category": "Entertainment: Video Games",
        "question": "How many classes are there in Team Fortress 2?",
        "correct_answer": "9",
        "incorrect_answers": ["10", "8", "7"],
    },
]
